### ISSUE TITLE
DROID CSV did not run on files, only top level directories in data directory

### ISSUE THREAD

**Issue by eamonsmallwood** [kaust-library/ArchiveAutomation#11]
[004_001_0001.csv](https://github.com/kaust-library/ArchiveAutomation/files/9655094/004_001_0001.csv)

Hi Marcelo,

We need the DROID module to generate metadata for all the content files from within the directory. In this case about 400 PDF files. 

The script needs to be recursive to make sure that we get DROID data for all content files within a directory, regardless of the internal structure of the directory.

**Comment by eamonsmallwood** [comment]
400 PDF files was a rough estimate :)

**Comment by marcelomgarcia** [comment]
It seems that we have to add the option to recurse into the subdirectories: `--recurse`. This option was added to the command to run `droid`:

```
droid_cmd = f"{droid_exec_path} -a {droid_bag_path} --recurse -p {acc_number}.droid
```

I did a quick test, and it seems to be working. I added a subfolder, and it appeared in the `.csv` file:

```
(...)
"4","3","file:/C:/Users/garcm0b/Work/000_000_0000/data/boat_trip_pictures/my_subfolder/"...
"14","4","file:/C:/Users/garcm0b/Work/000_000_0000/data/boat_trip_pictures/my_subfolder/KAUST_Seeds.zip"...
"11","4","file:/C:/Users/garcm0b/Work/000_000_0000/data/boat_trip_pictures/my_subfolder/LeslieLamport_2.jpg"...
(...)
```

**Comment by marcelomgarcia** [comment]
This issue seems to be solved. If needed, we reopen.
