### ISSUE TITLE
Cleanup completed SIP .cfg file

### ISSUE THREAD

**Issue by eamonsmallwood** [kaust-library/ArchiveAutomation#13]
Prerequisite - Preservica SIP ingest verification (#12) is completed. 

Once the SIP has been successfully completed and verified, move the SIP .cfg file to C:\Program Files\ArchiveAutomation\complete.

**Comment by marcelomgarcia** [comment]
I think I will not be able to do the move/rename with the script `archiveautomation` because OS will block saying that the `cfg` file is in use.

**Comment by marcelomgarcia** [comment]
This is not possible to do from the workflow script itself. We will need a third tool/script for renaming/moving the `cfg` files after the workflow is complete.

**Comment by marcelomgarcia** [comment]
This is not possible to do from the workflow script itself. We will need a third tool/script for renaming/moving the cfg files after the workflow is complete.
