### ISSUE TITLE
Multiple JHove modules

### ISSUE THREAD

**Issue by marcelomgarcia** [kaust-library/ArchiveAutomation#8]
We should be able to specify more than one module, and loop over it. Like

```
jhove_module = jpeg-hul,  mpeg-hul, pdf-hul
```

and then,

```
for mm in jhove_modules:
    jhove -m {mm} ...
```

**Comment by marcelomgarcia** [comment]
Add JHove modules to the configuration file (`.cfg`)

* AIFF-hul 
* ASCII-hul 
* GIF-hul 
* GZip-kb 
* HTML-hul 
* JPEG-hul 
* JPEG2000-hul 
* PDF-hul  
* TIFF-hul 
* UTF8-hul 
* WARC-kb 
* WAVE-hul 
* XML-hul

Like the example below

```
AIFF-hul = True
ASCII-hul = False
(...)
```

**Comment by marcelomgarcia** [comment]
Eamon is testing.

**Comment by eamonsmallwood** [comment]
I confirm multiple jhove modules can be run on a SIP. Tested and successfully ran all modules on a test ingest.
